[v1]
"bat 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat.exe"]
"bottom 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm.exe"]
"broot 1.36.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["broot.exe"]
"cargo-binstall 1.6.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall.exe"]
"coreutils 0.0.26 (registry+https://github.com/rust-lang/crates.io-index)" = ["coreutils.exe"]
"ddh 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["ddh.exe"]
"diskonaut 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["diskonaut.exe"]
"gfold 4.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["gfold.exe"]
"git-delta 0.17.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta.exe"]
"grex 1.4.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex.exe"]
"hyperfine 1.18.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine.exe"]
"just 1.25.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["just.exe"]
"kondo 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["kondo.exe"]
"nu 0.90.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu.exe"]
"ouch 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["ouch.exe"]
"procs 0.14.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs.exe"]
"ripgrep 14.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg.exe"]
"rnr 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["rnr.exe"]
"rust-parallel 1.18.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rust-parallel.exe"]
"sd 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sd.exe"]
"tealdeer 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr.exe"]
"trippy 0.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trip.exe"]
"uiua 0.10.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["uiua.exe"]
"zoxide 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide.exe"]
